// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/resume": {
    params: {};
  };
  "/resume/generator": {
    params: {};
  };
  "/resume/:id": {
    params: {
      "id": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/resume" | "/resume/generator" | "/resume/:id" | "/*";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "./routes/protected-layout.tsx": {
    id: "routes/protected-layout";
    page: "/" | "/resume" | "/resume/generator" | "/resume/:id";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/resume/index.tsx": {
    id: "routes/resume/index";
    page: "/resume";
  };
  "./routes/resume/generator.tsx": {
    id: "routes/resume/generator";
    page: "/resume/generator";
  };
  "./routes/resume/detail.tsx": {
    id: "routes/resume/detail";
    page: "/resume/:id";
  };
  "./routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};